"""Added recovery_estimated column

Revision ID: fe4c3ed9ae33
Revises: c51abc03a8c7
Create Date: 2026-03-18 15:19:14.530299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe4c3ed9ae33'
down_revision = 'c51abc03a8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recovery_estimated', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_logs', schema=None) as batch_op:
        batch_op.drop_column('recovery_estimated')

    # ### end Alembic commands ###
